name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup LTS Version of NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install all Dependencies
        working-directory: ./pipeline
        run: npm ci
      - name: Run Unit Tests
        working-directory: ./pipeline
        run: npm run test
      - name: Build App
        working-directory: ./pipeline
        run: npm run build
